[package]
name = "problem-solving"
version = "0.1.0"
edition = "2021"

[features]
default = ["solution1"]
solution1 = []
solution2 = []
solution3 = []

[dependencies]

[lints.clippy]
pedantic = "warn"
